In [ ]:
import keras.backend as K
import numpy as np
from keras import Input, layers
from keras.models import Model

In [ ]:
# custom filter
def my_filter(shape, dtype=None):

    f = np.array([
            [[[1]], [[0]], [[-1]]],
            [[[1]], [[0]], [[-1]]],
            [[[1]], [[0]], [[-1]]]
        ])
    assert f.shape == shape
    return K.variable(f, dtype='float32')

In [ ]:
#dummy example input
input_mat = np.array([
    [ [4], [9], [2], [5], [8], [3] ],
    [ [3], [6], [2], [4], [0], [3] ],
    [ [2], [4], [5], [4], [5], [2] ],
    [ [5], [6], [5], [4], [7], [8] ],
    [ [5], [7], [7], [9], [2], [1] ],
    [ [5], [8], [5], [3], [8], [4] ]
])

# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 6, 6, 1))

In [ ]:
#dummy model
def build_model():
    input_tensor = Input(shape=(6,6,1))

    x = layers.Conv2D(filters=1, 
                      kernel_size = 3,
                      kernel_initializer=my_filter,
                      strides=1, 
                      padding='valid') (input_tensor)

    model = Model(inputs=input_tensor, outputs=x)
    return model

In [ ]:
#Testing
model = build_model()
out = model.predict(input_mat)
print(out)

[[[[ 0.]
   [ 6.]
   [-4.]
   [ 5.]]

  [[-2.]
   [ 4.]
   [ 0.]
   [-1.]]

  [[-5.]
   [ 0.]
   [ 3.]
   [ 6.]]

  [[-2.]
   [ 5.]
   [ 0.]
   [ 3.]]]]
